version: "3"

services:

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            # - ../laravel/:/var/www/
        working_dir: /var/www/
  
    php:
        build: ./php/
        user: $user
        container_name: php
        volumes:
            - ../laravel/:/var/www/
    
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Tokyo
        volumes:
            - ./mysql/my.cnf:/etc/mysql/my.cnf
    
    # node:
    #     image: node:lts-alpine
    #     container_name: node
    #     volumes:
    #         - ../laravel:/mnt/laravel
    #     working_dir: /mnt/laravel
    #     tty: true

    # # laravel echo
    # laravel-echo-server:
    #     build: ./laravel-echo
    #     container_name: laravel-echo
    #     ports:
    #       - 6001:6001
    #     volumes:
    #       - ./laravel-echo/:/work:cached

    # redis:
    #     image: redis:5
    #     container_name: redis
    #     ports:
    #       - 6379:6379